# @package _global_

defaults:
  - /base
  - /task: NBitFlipFLop
  - /trainer: trainer
  - /model: rnn_tanh
  - _self_

  # OVERRIDES
#  - override /model: rnn_tanh_Dale

display_figures: False
n_nets: 10