# @package _global_

defaults:
  - ../task: GoNoGo
  - ../trainer: trainer
  - ../model: rnn_tanh_Dale
  - _self_

  # OVERRIDES
#  - override /model: rnn_tanh_Dale
#  - override /trainer: trainer_debug

display_figures: False
n_nets: 1
