import itertools
import numpy as np
from trainRNNbrain.tasks.TaskNBitFlipFlop import TaskNBitFlipFlop


class TaskNBitFlipFlopWalsh(TaskNBitFlipFlop):
    """k-bit flip-flop with ONE output: a random Walsh polynomial of the bit states.

    Inputs and bit dynamics are TaskNBitFlipFlop's (k pulse-train channels, each bit holding the
    sign of its last pulse), with two changes to the generator:
      * every bit is set by a pulse of random sign in steps 0..n_flip-1, so the joint state is
        defined from t=0 and each trial starts at a random vertex of the hypercube;
      * `mu_total` replaces `mu`: each bit gets mu_total/k expected pulses per trial, so the joint
        state changes about the same number of times per trial at every k (matched temporal demand);
      * with `always_flip` (default) every pulse carries the sign OPPOSITE to the bit's current
        state, so every event flips its bit and moves y. The network still implements a set/reset
        flip-flop exactly as in the plain task (it never needs its own state to apply a pulse);
        only the generator's sign choice changes, from i.i.d. to alternating.
    The target is
        y(t) = sum_{S non-empty, |S| <= degree} c_S prod_{i in S} b_i(t) / sqrt(sum c_S^2),
    with c_S drawn i.i.d. N(0,1) once from `coef_seed` (shared by every network), so y has unit
    variance over uniformly random states. On +-1 states the subset products are the Walsh basis, so
    y is one random linear combination of all sum_{m<=degree} C(k,m) basis functions: the read-out
    is one channel at every k, and `degree` is the demand knob at fixed k (rows are nested - y_d is
    the low-order part of y_k). Coefficients are indexed by binary mask m = 1..2^k-1 (bit j of m
    <=> bit j in S); `self.subsets[m-1]` is the tuple of bit indices.
    """

    def __init__(self, n_steps, n_inputs, n_outputs, mu_total, n_flip_steps, degree=None,
                 coef_seed=0, always_flip=True, batch_size=256, seed=None):
        """Args as TaskNBitFlipFlop except: mu_total (expected pulses per trial summed over bits),
        degree (max subset size in the sum; None = n_inputs), coef_seed (seed of the coefficient
        draw), always_flip (every pulse flips its bit; False = i.i.d. signs as the parent).
        n_outputs must be 1."""
        if n_outputs != 1:
            raise ValueError(f"n_outputs must be 1, got {n_outputs}")
        TaskNBitFlipFlop.__init__(self, n_steps, n_inputs, n_outputs, mu_total / n_inputs,
                                  n_flip_steps, batch_size, seed)
        k = n_inputs
        self.mu_total = mu_total
        self.degree = k if degree is None else int(degree)
        self.coef_seed = coef_seed
        self.always_flip = always_flip
        self.subsets = [tuple(j for j in range(k) if m >> j & 1) for m in range(1, 2 ** k)]
        c = np.random.default_rng(coef_seed).standard_normal(2 ** k - 1)
        c[[len(s) > self.degree for s in self.subsets]] = 0.0
        self.coefs = c / np.sqrt((c ** 2).sum())

    def spec(self):
        """Everything that fixes the target, for saving next to a trained network: the normalised
        coefficient vector by mask, the subset (bit-index) list, and the generator settings."""
        return {"coefs": self.coefs.tolist(), "subsets": [list(s) for s in self.subsets],
                "coef_seed": self.coef_seed, "degree": self.degree, "n_inputs": self.n_inputs,
                "mu_total": self.mu_total, "always_flip": self.always_flip,
                "n_flip_steps": self.n_flip, "n_steps": self.n_steps, "task_seed": self.seed}

    def walsh(self, bits, coefs=None):
        """Weighted sum of subset products, y = sum_m coefs[m-1] * prod_{j in m} bits[j].

        Args:
            bits: array (k, ...) of bit states in {-1, +1};
            coefs: (2**k-1,) weights by mask; default self.coefs.
        Returns:
            array (...) - the sum. Products are generated by depth-first recursion over subsets,
            so only k intermediate arrays are alive (the hyper task stores all 2^k-1).
        """
        coefs = self.coefs if coefs is None else coefs
        k = bits.shape[0]
        y = np.zeros(bits.shape[1:])

        def rec(j0, mask, prod):
            for j in range(j0, k):
                m, p = mask | (1 << j), prod * bits[j]
                if coefs[m - 1] != 0.0:
                    y[...] += coefs[m - 1] * p
                rec(j + 1, m, p)
        rec(0, 0, np.ones(bits.shape[1:]))
        return y

    def _finish(self, inp, bits, s0):
        """Apply the initial state s0 (k,) or (k, B): write the initial pulses, fill the target
        before the first pulse, and with always_flip re-sign every pulse to alternate from s0.
        Returns (inputs, walsh target with a leading channel axis, full bit states)."""
        if self.always_flip:
            # cnt = number of pulse onsets up to and including t (per bit, per trial); the i-th
            # pulse carries sign s0*(-1)^i and the state after it is the same value.
            on = (inp != 0) & (np.roll(inp, 1, axis=1) == 0)
            cnt = np.cumsum(on, axis=1)
            bits = s0[:, None] * np.where(cnt % 2 == 0, 1.0, -1.0)
            inp = np.where(inp != 0, bits, 0.0)
        else:
            bits = np.where(bits != 0, bits, s0[:, None])
        inp[:, :self.n_flip] = s0[:, None]
        return inp, self.walsh(bits)[None], bits

    def generate_input_target_stream(self):
        """One trial; returns (input (k, T), target (1, T), condition with the initial state)."""
        inp, bits, cond = TaskNBitFlipFlop.generate_input_target_stream(self)
        s0 = np.where(self.rng.random(self.n_inputs) < 0.5, -1.0, 1.0)
        inp, y, bits = self._finish(inp, bits, s0)
        cond["init"] = s0.tolist()
        return inp, y, cond

    def get_batch(self, shuffle=False):
        """A batch; returns (inputs (k, T, B), targets (1, T, B), conditions) - see the parent."""
        inp, bits, cond = TaskNBitFlipFlop.get_batch(self, shuffle=shuffle)
        s0 = np.where(self.rng.random((self.n_inputs, inp.shape[-1])) < 0.5, -1.0, 1.0)
        inp, y, bits = self._finish(inp, bits, s0)
        for b, c in enumerate(cond):
            c["init"] = s0[:, b].tolist()
        return inp, y, cond

    def bit_states(self, inputs):
        """Recover the (k, T, B) bit states from an input batch (forward-fill of pulse signs)."""
        ev = np.where(inputs != 0, inputs, 0.0)
        pos = np.where(ev != 0, np.arange(inputs.shape[1])[None, :, None], 0)
        return np.take_along_axis(ev, np.maximum.accumulate(pos, axis=1), axis=1)

    def spectrum(self, y_hat, bits):
        """Exact Walsh coefficients of a network's output, for the 'which latent variables were
        built' read-out.

        Args:
            y_hat: (T, B) or (1, T, B) output; bits: (k, T, B) bit states in {-1, +1}.
        Returns:
            (2**k-1,) recovered coefficient per mask (compare with self.coefs), and the number of
            joint states never visited (their mean is taken as 0). Averages y_hat within each joint
            state first, then transforms the 2^k-entry table, so the basis is exactly orthonormal.
        """
        k = bits.shape[0]
        y_hat = np.asarray(y_hat).reshape(bits.shape[1:])
        idx = ((bits > 0).astype(int) * (1 << np.arange(k))[:, None, None]).sum(0).ravel()
        table = np.bincount(idx, weights=y_hat.ravel(), minlength=2 ** k)
        n = np.bincount(idx, minlength=2 ** k)
        table = np.where(n > 0, table / np.maximum(n, 1), 0.0)
        states = np.array([[1.0 if s >> j & 1 else -1.0 for j in range(k)] for s in range(2 ** k)]).T
        return np.array([np.mean(table * np.prod(states[list(S)], axis=0)) for S in self.subsets]), int((n == 0).sum())


if __name__ == "__main__":
    for k, deg in ((3, 3), (6, 6), (8, 8), (8, 2)):
        task = TaskNBitFlipFlopWalsh(n_steps=300, n_inputs=k, n_outputs=1, mu_total=8,
                                     n_flip_steps=10, degree=deg, batch_size=256, seed=0)
        parent = TaskNBitFlipFlop(n_steps=300, n_inputs=k, n_outputs=k, mu=8 / k, n_flip_steps=10,
                                  batch_size=256, seed=0)
        inp, y, cond = task.get_batch()
        inp0, bits0, cond0 = parent.get_batch()
        assert inp.shape == (k, 300, 256) and y.shape == (1, 300, 256)
        assert np.array_equal(inp[:, 10:] != 0, inp0[:, 10:] != 0), "pulse timing after the init pulse must be the parent's"
        assert (inp[:, :10] != 0).all(), "every bit pulsed in steps 0-9"
        bits = task.bit_states(inp)
        assert (np.abs(bits) == 1).all(), "state defined at every step"
        on = (inp != 0) & (np.roll(inp, 1, axis=1) == 0); on[:, 0] = False
        assert np.array_equal(np.sign(inp[on]), -np.roll(bits, 1, axis=1)[on]), "every pulse flips its bit"
        # independent construction: itertools subsets + np.prod, unnormalised coefficient draw
        c = np.random.default_rng(0).standard_normal(2 ** k - 1)
        ref = np.zeros((300, 256)); tot = 0.0
        for r in range(1, deg + 1):
            for S in itertools.combinations(range(k), r):
                m = sum(1 << j for j in S); ref += c[m - 1] * np.prod(bits[list(S)], axis=0); tot += c[m - 1] ** 2
        assert np.allclose(y[0], ref / np.sqrt(tot)), "target != independent Walsh sum"
        pulses = on.sum((0, 1)).mean()  # spontaneous pulses per trial (excluding the k init pulses)
        changes = (np.diff(y[0], axis=0) != 0).sum(0).mean()
        rec, unvisited = task.spectrum(y, bits)
        assert np.allclose(rec, task.coefs, atol=1e-9) or unvisited > 0, "spectrum must recover the coefficients"
        print(f"k={k} degree={deg}: {int((task.coefs != 0).sum())} terms; y var {y.var():.3f}, range [{y.min():.2f}, {y.max():.2f}]; "
              f"pulses/trial {pulses:.1f} (mu_total 8), y changes/trial {changes:.1f}; unvisited states {unvisited}/{2 ** k}; "
              f"spectrum max err {np.abs(rec - task.coefs).max():.1e}")
    print("OK")
